# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a25bfadfeaadf36fb8a9e17af63f5bb481569b70784ddf66cbadc4bf1f66e41fc073ad98c525317b622c77a69c4089c0905c39581e245696df51b6518e2ca9b3

test:
  secret_key_base: 344ce525fc81833765d97b48c6f0bf3c25cc5b1643a30a4fb58e170267061dba1086f56a182549d90343b0b4471e9e550c7b3db76010e29baf154be446062ce7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
